version: '3.1'

services:

  uos:
    build: .
    image: uos
    restart: always
    ports:
      - 3000:3000

  db:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
