# When a push occurs to the master branch (such as a pull request to master,
# or code directly pushed to master), analyze the gitlog according to
# https://www.conventionalcommits.org/en/v1.0.0/ and bump the package.json
# file accordingly.
#
# This also notifies Azure of a new version, so the build pipeline will run.
# 
# This behavior can be prevented by including "[skip ci]"
# in the commit log message of the merge.
# 
name: Publish

on:
  push:
    branches: [master]

jobs:
  version:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Perform a clean install of modules
        run: npm ci
      - name: Remove old documentation
        run: rm -rf docs/
      - name: Regenerate documentation with new version number
        run: npm run doc
      - name: Add changes and remove deletions
        run: git add -A docs/
      - name: Set git email
        run: git config user.email "automated"
      - name: Set git user
        run: git config user.name "CI Workflow"
      - name: Commit doc update
        run: git commit -m "generate docs"
      - name: Update version
        run: docker run -v $(pwd):/repo ckxng/standardversion
      - name: Push repo
        run: git push --follow-tags origin master

  deploy-using-azure-pipelines:
    needs: version
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger an Azure Pipeline to deploy the app'
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/662-universityofscouting/University%20of%20Scouting'
        azure-pipeline-name: 'Longhorn-Council-BSA.universityofscouting' 
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
